version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app

  php:
    image: php:alpine
    volumes:
      - ./app:/var/www/html
      - ./app/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - app

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - app

volumes:
  pgdata:

networks:
  app:
    driver: bridge
