services:
  web:
    image: nginx:alpine
    ports:
        - "8000:80"
    volumes:
        - .:/usr/share/nginx/html
    networks:
        - app
  db:
    build: 
        context: postgres
    environment:
        POSTGRES_PASSWORD: postgres
    networks:
        - app
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8432:80"
    networks:
      - app
    environment:
       PGADMIN_DEFAULT_EMAIL: test@docker.fr
       PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
networks:
    app:
        driver: bridge